baseURL = 'https://mihailupoiu.github.io/community-box-fire/'
languageCode = 'es'
title = 'Community Box Fire - Directorio Profesional'
defaultContentLanguage = 'es'

# Enable tags
[taxonomies]
  tag = "tags"

# Site parameters
[params]
  description = "Directorio profesional de la comunidad Box Fire"
  mainSiteURL = "https://boxfirespain.com"
  images = ["images/og-image.jpg"]

# Menu
[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Profesionales"
    url = "/professionals/"
    weight = 2
  [[menu.main]]
    name = "Profesiones"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "Box Fire"
    url = "https://boxfirespain.com"
    weight = 4

# Make sure URLs include the base path in production
canonifyURLs = true

# Markdown processing configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = false
    [markup.goldmark.parser]
      autoHeadingID = true
      wrapStandAloneImageWithinParagraph = false

  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = false

# Ignore HTML warnings
ignoreLogs = ['warning-goldmark-raw-html']